[package]
name = "toggl-track-cli"
version = "0.1.0"
edition = "2024"
description = "The unofficial CLI client for Toggl Track"
license = "MIT"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
